### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by snova-varunkrishna** [sambanova/generative_data_prep#105]
I'm unable to install the package on my Mac (Sonoma 14.1 on Apple M3 Pro) using the following commands
```
git clone https://github.com/sambanova/generative_data_prep.git
cd generative_data_prep
pip install .
```
I get the following error:
```
ERROR: Could not find a version that satisfies the requirement torch>=2.3 (from sambanova-generative-data-prep) (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch>=2.3
```

I've tried the following Python versions (all stable versions) and got the same error:
3.9.19
3.10.14
3.11.9
3.12.3
I suspect the Python version might not be the issue here. Others have run into similar issues on the M3 chip: https://github.com/pytorch/executorch/issues/3670

I've also tried running
`conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 -c pytorch`
and
`pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0`
from https://pytorch.org/get-started/previous-versions/ but I get the same error

**Comment by snova-zoltanc** [comment]
@snova-varunkrishna Could you add your fix to this issue so we can close this? You used docker or something?

**Comment by snova-zoltanc** [comment]
Closed because this is a Mac chip issue, users should use a different environment or machine until Mac M3 chip bug is fixed
