### ISSUE TITLE
Greedy Truncate Right Bug

### ISSUE THREAD

**Issue by snova-virens** [sambanova/generative_data_prep#50]
Greedy Truncate Right could produce a sequence of all prompt tokens if the prompt is longer than the max sequence length.

**Comment by snova-zoltanc** [comment]
Wait this is not the case, because we filter for those sequences after tokenizing in https://github.com/sambanova/generative_data_prep/blob/main/generative_data_prep/processors/article_tokenizer.py function called "_remove_prompt_only_sequences"
