### ISSUE TITLE
KeyError during balancing if fewer lines in input file than splits

### ISSUE THREAD

**Issue by snova-leonz** [sambanova/generative_data_prep#54]
I was getting an error during balancing, like `KeyError: "Unable to open object (object 'input_ids' doesn't exist)"`

after a little digging around, I think the balancing assumes that each of the splits of data has been initialized. but if the input file has fewer lines than number of splits, then some of them will not be

in my case, my input file was a single line with all of the data. I had interpreted [this section](https://github.com/sambanova/generative_data_prep#input-format) as it being okay, esp the third line

**Comment by snova-zoltanc** [comment]
Completed with PR https://github.com/sambanova/generative_data_prep/pull/69
